/* Packs assets/tex/*.jpg into js/vendor/assets.js as data URIs.
     node tools/pack-assets.js
   WebGL refuses images loaded from file:// (they count as another
   origin), so the textures travel inside a script instead - the game
   then works double-clicked from disk and bundled into one file. */
const fs = require('fs'), path = require('path');
const ROOT = path.join(__dirname, '..');
const dir = path.join(ROOT, 'assets', 'tex');
const out = {};
for (const f of fs.readdirSync(dir).filter(f => f.endsWith('.jpg')).sort())
  out[f.replace(/\.jpg$/, '')] = 'data:image/jpeg;base64,' + fs.readFileSync(path.join(dir, f)).toString('base64');
const js = '/* generated by tools/pack-assets.js - textures from Poly Haven (CC0) */\n' +
           'var ASSETS = ' + JSON.stringify(out, null, 1) + ';\n';
fs.writeFileSync(path.join(ROOT, 'js', 'vendor', 'assets.js'), js);
console.log(Object.keys(out).length + ' textures, ' + (js.length/1024).toFixed(0) + ' kB -> js/vendor/assets.js');
