/* Packs assets/tex/*.jpg and assets/models/*.glb into js/vendor/assets.js
   as data URIs.       node tools/pack-assets.js
   WebGL refuses images loaded from file:// (they count as another
   origin), and fetch() cannot read files next to the page there either,
   so everything travels inside a script - the game then works
   double-clicked from disk and bundled into one file. */
const fs = require('fs'), path = require('path');
const ROOT = path.join(__dirname, '..');
const out = {};
const dirs = [['tex', '.jpg', 'image/jpeg'], ['models', '.glb', 'model/gltf-binary']];
/* the models the game uses (the pack has a fourth, near-identical man) */
const MODELS = ['man', 'man_suit', 'man_sleeves'];
for (const [dir, ext, mime] of dirs){
  const full = path.join(ROOT, 'assets', dir);
  if (!fs.existsSync(full)) continue;
  for (const f of fs.readdirSync(full).filter(f => f.endsWith(ext)).sort()){
    const key = f.slice(0, -ext.length);
    if (dir === 'models' && !MODELS.includes(key)) continue;
    out[(dir === 'models' ? 'model_' : '') + key] = 'data:' + mime + ';base64,' + fs.readFileSync(path.join(full, f)).toString('base64');
  }
}
const js = '/* generated by tools/pack-assets.js - textures from Poly Haven (CC0), ' +
           'people from Quaternius "Animated Men Pack" (CC0) */\n' +
           'var ASSETS = ' + JSON.stringify(out, null, 1) + ';\n';
fs.writeFileSync(path.join(ROOT, 'js', 'vendor', 'assets.js'), js);
console.log(Object.keys(out).length + ' assets, ' + (js.length/1024).toFixed(0) + ' kB -> js/vendor/assets.js');
